import "./styles/globals.css"
import Navbar from "./Components/NavBar/page"
import Sidebar from "./Components/Sidebar/page"
import Footer from "./Components/Footer/page"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }) {
  return (
    <html lang="he">
      <body>
        <div id="TopNavBar">
          <Navbar />
        </div>

        <div id="parent">
          <div id="LeftMenu">
            <Sidebar />
          </div>

          <div className="two">
            <main id="MainPage">{children}</main>
          </div>
        </div>

        <Footer />
      </body>
    </html>
  )
}
